services:
  nginx:
    image: docflow/docflow:nginx
    platform: linux/amd64
    build:
      dockerfile_inline: |
        FROM nginx:latest
    container_name: docflow-nginx
    networks:
      - docflow-network
    env_file: ./env/.env.development
    ports:
      - 80:${DOCKER_INTERNAL_NGINX_PORT}
      - 443:${DOCKER_INTERNAL_NGINX_SSL_PORT}
    volumes:
      - ./nginx/default.development.conf:/etc/nginx/conf.d/default.conf
    expose:
      - ${DOCKER_INTERNAL_NGINX_PORT}
      - ${DOCKER_INTERNAL_NGINX_SSL_PORT}
    depends_on:
      frontend:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ['CMD-SHELL', 'service nginx status || exit 1']
      interval: 10s
      timeout: 3s
      retries: 3
    restart: on-failure

  frontend:
    image: docflowteam/docflow:frontend
    platform: linux/amd64
    build:
      dockerfile: Dockerfile.development
    container_name: docflow-frontend
    networks:
      - docflow-network
    env_file:
      - ./env/.env.development
    ports:
      - 3000:${DOCKER_INTERNAL_FRONTEND_PORT}
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          memory: 1096M
    restart: on-failure

networks:
  docflow-network:
    driver: bridge
