services:
  nginx:
    image: docflowteam/docflow:nginx
    platform: linux/amd64
    build:
      dockerfile_inline: |
        FROM nginx:latest
    container_name: docflow-nginx
    networks:
      - docflow-network
    env_file: ./env/.env.production
    ports:
      - 80:${DOCKER_INTERNAL_NGINX_PORT}
      - 443:${DOCKER_INTERNAL_NGINX_SSL_PORT}
    volumes:
      - ./nginx/default.production.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    expose:
      - ${DOCKER_INTERNAL_NGINX_PORT}
      - ${DOCKER_INTERNAL_NGINX_SSL_PORT}
    depends_on:
      frontend:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ['CMD-SHELL', 'service nginx status || exit 1']
      interval: 10s
      timeout: 3s
      retries: 3
    restart: on-failure

  certbot:
    image: docflowteam/docflow:certbot
    platform: linux/amd64
    build:
      dockerfile_inline: |
        FROM certbot/certbot
    container_name: docflow-certbot
    networks:
      - docflow-network
    env_file: ./env/.env.production
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    expose:
      - ${DOCKER_INTERNAL_NGINX_PORT}
      - ${DOCKER_INTERNAL_NGINX_SSL_PORT}
    depends_on:
      nginx:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
    entrypoint:
      "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: on-failure

  frontend:
    image: docflowteam/docflow:frontend
    platform: linux/amd64
    build:
      context: frontend
      dockerfile: Dockerfile.production
      args:
        VITE_FRONTEND_PORT: $VITE_FRONTEND_PORT
        VITE_BACKEND_URI: ${VITE_BACKEND_URI}
        VITE_BACKEND_PREFIX: ${VITE_BACKEND_PREFIX}
        VITE_FRONTEND_URI: ${VITE_FRONTEND_URI}
        VITE_BACKEND_PORT: ${VITE_BACKEND_PORT}
        VITE_COOKIE_ACCESS_TOKEN_NAME: ${VITE_COOKIE_ACCESS_TOKEN_NAME}
        VITE_COOKIE_REFRESH_TOKEN_NAME: ${VITE_COOKIE_REFRESH_TOKEN_NAME}
        VITE_COOKIE_OAUTH2_TOKEN_NAME: ${VITE_COOKIE_OAUTH2_TOKEN_NAME}
        VITE_COOKIE_DOMAIN: ${VITE_COOKIE_DOMAIN}
        VITE_COOKIE_SECRET: ${VITE_COOKIE_SECRET}
        VITE_JWT_SECRET: ${VITE_JWT_SECRET}
        VITE_JWT_ISSUER: ${VITE_JWT_SECRET}
        VITE_JWT_AUDIENCE: ${VITE_JWT_AUDIENCE}
        VITE_NGINX_PORT: ${VITE_NGINX_PORT}
    container_name: docflow-frontend
    networks:
      - docflow-network
    env_file:
      - ./env/.env.production
    ports:
      - 3000:${DOCKER_INTERNAL_FRONTEND_PORT}
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          memory: 1096M
    restart: on-failure

networks:
  docflow-network:
    driver: bridge
